### ISSUE TITLE
Update system font stack selector

### ISSUE THREAD

**Issue by alenvuletic** [Slicejack/bojler#27]
Update system font stack selector to look like this:

```css
body,
table td {
    color: $color-dark;
    font-family: 'Merriweather Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif !important; /* 2 */
}
```
